# Generated by Django 4.2.7 on 2023-11-25 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('about', models.CharField(blank=True, default='', max_length=1000)),
                ('private', models.BooleanField(default=False)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('brown', 'Brown'), ('black', 'Black'), ('pink', 'Pink')], default='black', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=1000)),
                ('content', tinymce.models.HTMLField(blank=True, default='')),
                ('notebook', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='journal_application.notebook')),
            ],
        ),
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=1000)),
                ('notebook', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='journal_application.notebook')),
            ],
        ),
    ]
