# Generated by Django 4.2.7 on 2023-11-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_application', '0002_remove_notebook_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
