# Generated by Django 4.2.7 on 2023-11-02 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_application', '0003_notebook_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
