# Generated by Django 4.2.7 on 2023-11-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_application', '0004_remove_notebook_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('brown', 'Brown'), ('black', 'Black'), ('pink', 'Pink'), ('white', 'White')], default='black', max_length=10),
        ),
    ]
