# Generated by Django 4.2.7 on 2023-11-25 04:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_application', '0005_notebook_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
